config/routes.rb
Rails.application.routes.draw do
  resources :main_searches, only: [:new, :create]

  get 'main_searches/show', 
        controller: :main_searches, action: :show,
        as: :show_main_search

  get 'host_reports/show', 
        controller: :host_reports, action: :show,
        as: :show_host_report

  get 'host_reports/mail/new', 
        controller: :host_reports, action: :new_mail,
        as: :new_mail_host_report

  post 'host_reports/mail', 
        controller: :host_reports, action: :create_mail,
        as: :create_mail_host_report

  post 'host_reports/update', 
        controller: :host_reports, action: :update,
        as: :update_host_report

  resources :event_rules
  resources :signatures do
    member do
      get 'pcap'
      delete 'destroy_events'
    end
  end
  resources :events, except: [:new, :create] do
    member do
      get 'packet'
    end
  end

  mount Wobauth::Engine, at: '/auth'

  root 'signatures#index', filter: 'current'
end

app/models/signature.rb
class Signature < ApplicationRecord
  include SignatureConcerns
  # -- associations
  has_many :events, foreign_key: :alert_signature_id, primary_key: :signature_id

  # -- configuration
  serialize :references, JSON
  ACTIONS = ['drop', 'ignore', 'normal', 'alert']
  # -- validations and callbacks
  validates :signature_id, presence: true, uniqueness: true
  validates :signature_info, presence: true
  validates :action, :allow_blank => false,
            :inclusion => {
              in: Signature::ACTIONS,
              message: "Select one of #{Signature::ACTIONS.join(", ")}"
            }


end

app/controllers/signatures_controller.rb
class SignaturesController < ApplicationController
  before_action :set_signature, only: [:show, :edit, :update, :destroy]
  before_action :get_signatures, only: [:index]
  before_action :add_breadcrumb_show, only: [:show]

  # GET /signatures
  def index
    respond_with(@signatures)
  end

  # GET /signatures/1
  def show
    respond_with(@signature)
  end

  # GET /signatures/new
  def new
    @signature = Signature.new
    respond_with(@signature)
  end

  # GET /signatures/1/edit
  def edit
  end

  # POST /signatures
  def create
    @signature = Signature.new(signature_params)

    @signature.save
    respond_with(@signature)
  end

  # PATCH/PUT /signatures/1
  def update
    @signature.update(signature_params)
    respond_with(@signature)
  end

  # DELETE /signatures/1
  def destroy
    @signature.destroy
    respond_with(@signature)
  end

  def destroy_events
    if params[:commit] == t('actions.destroy_all')
      @signature.events.destroy_all
    elsif params[:commit] == t('actions.destroy_marked')
      @signature.events.where(['id IN (?)', event_ids]).destroy_all
    elsif params[:commit] == t('actions.all_done')
      @signature.events.update_all(done: true)
    elsif params[:commit] == t('actions.marked_done')
      @signature.events.where(['id IN (?)', event_ids]).update_all(done: true)
    else
      @error = "unknown commit"
    end
    redirect_to signature_path(@signature)
  end

  # send packet data for download
  def pcap
    send_data @signature.to_pcap,
      filename: "signature_#{@signature.signature_id}.pcap",
      disposition: 'attachment',
      type: 'Application/vnd.tcpdump.pcap'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_signature
      @signature = Signature.find(params[:id])
    end

    # how to use the parameter :filter
    # /signatures?by_network=<ip>
    # /signatures?filter=current : active sigs with events within 24h
    # /signatures?filter=current&since=48 : active sigs with events within 48h
    # /signatures?filter=ignored : ignored signatures
    # /signatures?filter=all     : all signatures (including sigs without events)
    # a signature is active if signature.drop=false and signature.ignore=false

    def get_signatures
      @filter_info = t('lackmus.signatures.choosen_filter') + ": "
      @signatures  = Signature.active.joins(:events)

      if params[:ip]
        @signatures = @signatures.merge(Event.by_network(params[:ip]))
      end
      if params[:filter] == 'ignored'
        @signatures   = Signature.ignored.includes(:events)
        @filter_info += t('lackmus.signatures.ignored')
      elsif params[:filter] == 'current'
        if params[:since].present?
          hours = (params[:since].to_i).hours
        else
          hours = 24.hours
        end
        since = Time.now - hours
        @filter_info += t('lackmus.signatures.since') + " " + since.to_s
        @signatures = @signatures.merge(Event.active).merge(Event.since(since)).distinct
      elsif params[:filter] =~ /\A(today|yesterday|thisweek|lastweek)\z/
        match = $~.to_s
        @filter_info = t('lackmus.signatures.' + match)
        @signatures = @signatures.merge(Event.active).merge(Event.send(match)).distinct
      elsif params[:filter] == 'all'
        @signatures = Signature.all
        @filter_info += t('lackmus.signatures.all')
      elsif params[:filter] == 'unassigned'
        @signatures = @signatures.merge(Event.unassigned).distinct
        @filter_info += t('lackmus.signatures.unassigned')
      else
        @signatures = @signatures.merge(Event.active).distinct
        @filter_info += t('lackmus.signatures.active')
      end
    end

    def event_ids
      params[:event_ids] || []
    end

    # Only allow a trusted parameter "white list" through.
    def signature_params
      params.require(:signature).permit(:signature_id, :signature_info, :references, :action)
    end
end

app/helpers/signatures_helper.rb
module SignaturesHelper
 def signature_action_link(sig)
    link  = ""
    link += %Q[<div style="min-width:70px;">]
    link += %Q[ <div class="btn-group" role="group">]
    link +=       show_link(sig)
    link += %Q[  <button id="SigActionLinkDrop" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">]
    link += %Q[  </button>]
    link += %Q[  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="SigActionLinkDrop">]
    if can? :edit, sig
      link += link_to raw("<i class='fas fa-fw fa-pencil-alt'></i> #{t('actions.edit', model: t('activerecord.models.signature'))}"), edit_signature_path(sig), class: 'dropdown-item'
    end
    if can? :destroy, Event.new
      link += mark_events_done_link(sig)
      link += delete_events_link(sig)
    end
    link += link_to raw("#{icon_download} #{t('lackmus.wireshark')}") , pcap_signature_path(sig),
                    class: 'dropdown-item', title: t('lackmus.wireshark')
    link += %Q[  </div>]
    link += %Q[ </div> ]
    link += %Q[</div>]
    link.html_safe
  end

  def signature_id_link(signature)
    sig = Signature.where(signature_id: signature).first
    if sig.present?
      link_to(signature, signature_path(sig))
    else
      "#{signature}"
    end
  end

  def signatures_by_ip(ip)
    link_to("#{ip}", signatures_path(ip: ip)) + " " +
    host_report_link(ip)
  end

  def delete_events_link(sig, options = {})
    link_to raw("<i class='fas fa-fw fa-trash'></i> #{t('actions.destroy_all')}"),
      destroy_events_signature_path(sig, commit: t('actions.destroy_all')),
      method: :delete,
      data: {confirm: "#{t('lackmus.really')} #{t('actions.destroy_all')}?\n\n#{t('lackmus.truly')}"},
      class: options.fetch(:class, "dropdown-item")
  end

  def mark_events_done_link(sig, options = {})
    link_to raw("<i class='fas fa-fw fa-check'></i> #{t('actions.all_done')}"),
      destroy_events_signature_path(sig, {commit: t('actions.all_done')}),
      method: :delete,
      data: {confirm: "#{t('lackmus.really')} #{t('actions.all_done')}?"},
      class: options.fetch(:class, "dropdown-item")
  end

  def link_references(sig)
    return if sig.references.blank?
    sig.references.map {|s| linkedref(s) }.join("<br/>").html_safe
  end

  def linkedref(string)
    (type, text) = string.split(/,/)
    if type.downcase == "url"
      link_to text, "http://#{text}", target: '_blank'
    elsif type.downcase == "cve"
      link_to "CVE #{text}", "https://www.cvedetails.com/cve/CVE-#{text}/", target: '_blank'
    else
      string
    end
  end
end

app/views/signatures/_events.html.erb
<% content_for :head do %>
  <meta name="turbolinks-cache-control" content="no-cache">
<% end %>

<%= form_tag(
      destroy_events_signature_path(@signature),
      method: :delete, role: 'form'
    ) do %>

  <%= hidden_field_tag :filter, @filter %>

  <div class="form-group">

    <table id="eventsTable" class="table table-bordered table-striped table-sm dataTable">

    <thead>
      <tr>
	<th class="center nosort"><%= check_box_tag "checkAll" %></th>
	<th><%= t('attributes.sensor') %></th>
	<th><%= t('attributes.event_time') %></th>
	<th><%= t('attributes.src_ip') %></th>
	<th><%= t('attributes.src_port') %></th>
	<th><%= t('attributes.dst_ip') %></th>
	<th><%= t('attributes.dst_port') %></th>
	<th><%= t('attributes.proto') %></th>
	<th><%= t('attributes.http_hostname') %></th>
	<th class="nosort"></th>
      </tr>
    </thead>
    <tbody>

    <% events.each do |event| %>
      <%= content_tag_for(:tr, event) do %>
	<td class="center nosort"><%= check_box_tag "event_ids[]", event.id, false, class: "multicheck" %></td>
        <td><%= link_to(event.sensor, events_path(sensor: event.sensor)) %></td>
	<td><%= event.event_time.to_s(:precision) %></td>
	<td><%= signatures_by_ip(event.src_ip) %> / 
	    <%= IpLookup.hostname(event.src_ip) %> <br />
            <%= threatcrowd_link(ip: event.src_ip) %>
            <%= ipintel_link(ip: event.src_ip) %>
	</td>
	<td><%= event.src_port %></td>
	<td><%= signatures_by_ip(event.dst_ip) %> / 
	    <%= IpLookup.hostname(event.dst_ip) %> <br />
            <%= threatcrowd_link(ip: event.dst_ip) %>
            <%= ipintel_link(ip: event.dst_ip) %>
	</td>
	<td><%= event.dst_port %></td>
	<td><%= event.proto %></td>
        <td>
          <% unless event.http_hostname.blank? %>
            <%= link_to event.http_hostname, events_path(httphost: event.http_hostname) %>
            <br />
            <%= threatcrowd_link(domain: event.http_hostname) %>
          <% end %>
       </td>
	<td class="nowrap">
	  <%= show_link event %>
	  <%= delete_link event %>
	  <%= link_to icon_download, packet_event_path(event), 
		class: 'btn btn-secondary', title: "Download pcap file" %>
          <%= new_rule_from_event(event) %>
	</td>
      <% end %>
    <% end %>
    </tbody>
    </table>
  </div>

  <% if events.any? %>
  <div role="toolbar">
    <%= submit_tag(t('actions.marked_done'), class: "btn btn-primary",
          data: {confirm: "#{t('lackmus.really')} #{t('actions.marked_done')}?"})%>
    <%= submit_tag(t('actions.all_done'), class: "btn btn-warning",
          data: {confirm: "#{t('lackmus.really')} #{t('actions.all_done')}?"})%>
    <%= submit_tag(t('actions.destroy_marked'), class: "btn btn-danger",
          data: {confirm: "#{t('lackmus.really')} #{t('actions.destroy_marked')}?"})%>
  </div>
  <% end %>
<% end %> <!-- end form -->

app/views/signatures/_form.html.erb
<div class="container">
  <%= simple_form_for(@signature,
    html: { class: 'form-horizontal card' }) do |f| %>

    <div class="card-header">
      <%= form_legend %>
    </div>
    <div class="card-body">
      <%= f.input :signature_id
       %>
      <%= f.input :signature_info
       %>
      <%= f.input :category
       %>
      <%= f.input :severity
       %>
      <%= f.input :references
       %>
      <%= f.input :action, collection: Signature::ACTIONS, include_blank: false
       %>

      <%= f.button :submit, class: 'btn btn-primary' %>
      <%= cancel_button %>
    </div>
  <% end %>
</div>

app/views/signatures/_index.html.erb
<%= render partial: 'shared/filter_info' %>

<table id="signaturesTable" class="table table-bordered table-striped dataTable">
<thead>
  <tr>
    <th><%= t('attributes.signature_id') %></th>
    <th><%= t('attributes.signature_info') %></th>
    <th><%= t('attributes.category') %></th>
    <th>Sev.</th>
    <th><%= t('attributes.last_seen') %></th>
    <th><%= t('attributes.count') %></th>
    <th><%= t('attributes.action') %></th>
    <th></th>
  </tr>
</thead>
<tfoot>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</tfoot>
<tbody>

<% @signatures.each do |signature| %>
  <%= content_tag_for(:tr, signature) do %>
    <td><%= signature.signature_id %></td>
    <td><%= signature.signature_info %></td>
    <td><%= signature.category %></td>
    <td><%= signature.severity %></td>
    <td><%= signature.last_seen %></td>
    <td><%= signature.events_count %></td>
    <td><%= signature.action %></td>
    <td>
      <%= signature_action_link(signature) %>
    </td>
  <% end %>
<% end %>
</tbody>
</table>

<br />

<%= back_link %>
<%= new_link Signature %>
<%= link_to t('actions.reset_table'), "#", id: "reset_table", class: "btn btn-secondary" %>

app/views/signatures/index.html.erb
<% content_for :head do %>
  <meta name="turbolinks-cache-control" content="no-cache">
<% end %>

<h1><%= t('controller.signatures') %></h1>

<%= render 'index' %>

app/views/signatures/show.html.erb
<div class="card">
  <div class="card-header">
    <div class="signature_header">
      <%= @signature.signature_id %>
      <%= @signature.signature_info %>
    </div>
  </div>
  <div class="card-body">
    <div class="signature_subtitle">
      <%= @signature.category %> / Severity: <%= @signature.severity %>
    </div>

    <table class="table table-hover">
      <tr>
	<th class="w-25"><%= t('attributes.last_seen')%>:</th>
	<td class="w-75"><%= @signature.last_seen %></td>
      </tr>
      <tr>
	<th><%= t('attributes.count')%>:</th>
	<td><%= @signature.events.count %></td>
      </tr>
      <tr>
	<th><%= t('attributes.references')%>:</th>
	<td><%= link_references(@signature) %></td>
      </tr>
      <tr>
	<th><%= t('attributes.action')%>:</th>
	<td><%= @signature.action %></td>
      </tr>
    </table>

    <div role="toolbar">
      <%= back_link %>
      <%= edit_link(@signature) %>
      <%= delete_link(@signature) %>
      <%= link_to "Download PCAP", pcap_signature_path(@signature), class: 'btn btn-secondary' %>
    </div>
  </div>
</div>

<% if can? :read, Event %>
  <br />  
  <h2 class="mb-3"><%= t('controller.events') %></h2>
  <%= render partial: 'events', locals: { events: @signature.events.active.most_current(50) } %>
<% end %>