config/routes.rb
Rails.application.routes.draw do
  resources :main_searches, only: [:new, :create]

  get 'main_searches/show', 
        controller: :main_searches, action: :show,
        as: :show_main_search

  get 'host_reports/show', 
        controller: :host_reports, action: :show,
        as: :show_host_report

  get 'host_reports/mail/new', 
        controller: :host_reports, action: :new_mail,
        as: :new_mail_host_report

  post 'host_reports/mail', 
        controller: :host_reports, action: :create_mail,
        as: :create_mail_host_report

  post 'host_reports/update', 
        controller: :host_reports, action: :update,
        as: :update_host_report

  resources :event_rules
  resources :signatures do
    member do
      get 'pcap'
      delete 'destroy_events'
    end
  end
  resources :events, except: [:new, :create] do
    member do
      get 'packet'
    end
  end

  mount Wobauth::Engine, at: '/auth'

  root 'signatures#index', filter: 'current'
end

app/models/main_search.rb
class MainSearch
  attr_reader :filter_info, :options
  def initialize(options = {})
    @signature = nil; @ip = nil; @sensor = nil; @filter_info = ""
    @options = options.symbolize_keys
    if @query = options.fetch(:q, nil)
      if  is_ip?(@query) 
        @ip = @query
      elsif is_sensor?(@query)
        @sensor = @query
      elsif is_signature?(@query)
        @signature = @query
      end
    end
    # -- may be in simple query
    @ip        = options.fetch(:ip,     nil) if @ip.nil?
    @sensor    = options.fetch(:sensor, nil) if @sensor.nil?
    @signature = options.fetch(:signature, nil) if @signature.nil?
    # -- non simple query fields
    @http_hostname = options.fetch(:http_hostname, nil)
  end

  def events
    @events ||= find_events
  end

  def event_ids
    events.pluck(:id)
  end

  def signatures
    Signature.active.joins(:events).where("events.id in (?)", event_ids).distinct
  end

private
  attr_reader :ip, :sensor, :signature, :http_hostname

  def find_events
    events = Event.order("event_time DESC")
    events = events.where(["src_ip <<= :ip or dst_ip <<= :ip", ip: ip]) unless ip.nil?
    events = events.where(["sensor like :sensor", sensor: "%#{sensor}%"]) unless sensor.nil?
    events = events.where(alert_signature_id: signature) unless signature.nil?
    events = events.where("http_hostname like :hostname", hostname: "%#{http_hostname}") unless http_hostname.nil?
    @filter_info = events.to_sql
    events
  end

  def is_ip?(ip)
    !(IPAddr.new(ip) rescue nil).nil?
  end

  def is_sensor?(sensor)
    sensor =~ /\A[A-Za-z._-]+\z/
  end

  def is_signature?(signature)
    signature =~ /\A\d+\z/
  end
end

app/controllers/main_searches_controller.rb
class MainSearchesController < ApplicationController
  def new
    add_breadcrumb(t('actions.search'), new_main_search_path)
    @search = MainSearch.new
  end

  def create
    Rails.cache.write("MainSearch/#{current_user.id}", MainSearch.new(search_params.to_h),
                      expires_in: 1.day)
    redirect_to action: "show"
  end

  def show
    search = Rails.cache.read("MainSearch/#{current_user.id}")
    if search.nil?
      @search = MainSearch.new
      render action: 'new'
    else
      add_breadcrumb(t('lackmus.search_result'), show_main_search_path)
      if search.options.fetch(:layout, "") == 'Events'
        @events = search.events
        @filter_info = search.filter_info
        render template: 'main_searches/show_events'
      else
        @signatures = search.signatures
        @filter_info = search.filter_info
        render template: 'main_searches/show_signatures'
      end
    end
  end

private

  def search_params
    params.require(:search).permit(:q, :ip, :sensor, :signature, :http_hostname, :layout).reject{|_, v| v.blank?}
  end
end

app/views/main_searches/new.html.erb
<div class="container">
  <%= form_tag(main_searches_path, role: "form",
    class: 'form-horizontal card' ) do |f| %>
    <div class="card-header">
      <%= form_legend %>
    </div>
    <div class="card-body">
      <div class="form-group row">
	<label for="query" class="col-sm-2 col-form-label">
	  <%= t('attributes.query') %>
	</label>
	<div class="col-sm-9">
	  <input type="text" class="form-control" id="search_q" name="search[q]">
	</div>
      </div>
      <div class="form-group row">
	<label for="ip" class="col-sm-2 col-form-label">
	  <%= t('attributes.ip') %>
	</label>
	<div class="col-sm-9">
	  <input type="text" class="form-control" id="search_ip" name="search[ip]">
	</div>
      </div>
      <div class="form-group row">
	<label for="sensor" class="col-sm-2 col-form-label">
	  <%= t('attributes.sensor') %>
	</label>
	<div class="col-sm-9">
	  <input type="text" class="form-control" id="search_sensor" name="search[sensor]">
	</div>
      </div>
      <div class="form-group row">
	<label for="signature" class="col-sm-2 col-form-label">
	  <%= t('attributes.signature') %>
	</label>
	<div class="col-sm-9">
	  <input type="text" class="form-control" id="search_signature" name="search[signature]">
	</div>
      </div>
      <div class="form-group row">
	<label for="http_hostname" class="col-sm-2 col-form-label">
	  <%= t('attributes.http_hostname') %>
	</label>
	<div class="col-sm-9">
	  <input type="text" class="form-control" id="search_http_hostname" name="search[http_hostname]">
	</div>
      </div>
      <div class="form-group row">
	<label for="layout" class="col-sm-2 col-form-label">
	  <%= t('attributes.layout') %>
	</label>
	<div class="col-sm-9">
	  <%= select_tag "search[layout]", 
		options_for_select([ "Signatures", "Events" ], "Events"),
		class: "form-control"
	  %>
	</div>
      </div>
      <div class="form-group row">
	<div class="offset-sm-2 col-sm-9">
	  <button type="submit" class="btn btn-primary"><%= t('actions.search') %></button>
	  <%= cancel_button %>
	</div>
      </div>
    </div>
  <% end %>
</div>

app/views/main_searches/show.html.erb
<h1><%= t('lackmus.search_result') %></h1>

<%= render 'events/index' %>

app/views/main_searches/show_events.html.erb
<h1><%= t('lackmus.search_result') %></h1>

<%= render 'events/index' %>

app/views/main_searches/show_signatures.html.erb
<h1><%= t('lackmus.search_result') %></h1>

<%= render 'signatures/index' %>