config/routes.rb
Rails.application.routes.draw do
  resources :main_searches, only: [:new, :create]

  get 'main_searches/show', 
        controller: :main_searches, action: :show,
        as: :show_main_search

  get 'host_reports/show', 
        controller: :host_reports, action: :show,
        as: :show_host_report

  get 'host_reports/mail/new', 
        controller: :host_reports, action: :new_mail,
        as: :new_mail_host_report

  post 'host_reports/mail', 
        controller: :host_reports, action: :create_mail,
        as: :create_mail_host_report

  post 'host_reports/update', 
        controller: :host_reports, action: :update,
        as: :update_host_report

  resources :event_rules
  resources :signatures do
    member do
      get 'pcap'
      delete 'destroy_events'
    end
  end
  resources :events, except: [:new, :create] do
    member do
      get 'packet'
    end
  end

  mount Wobauth::Engine, at: '/auth'

  root 'signatures#index', filter: 'current'
end

app/models/host_report.rb
# dummy for cancancan yet, may be later use as report model
class HostReport
end

app/models/signature.rb
class Signature < ApplicationRecord
  include SignatureConcerns
  # -- associations
  has_many :events, foreign_key: :alert_signature_id, primary_key: :signature_id

  # -- configuration
  serialize :references, JSON
  ACTIONS = ['drop', 'ignore', 'normal', 'alert']
  # -- validations and callbacks
  validates :signature_id, presence: true, uniqueness: true
  validates :signature_info, presence: true
  validates :action, :allow_blank => false,
            :inclusion => {
              in: Signature::ACTIONS,
              message: "Select one of #{Signature::ACTIONS.join(", ")}"
            }


end

app/controllers/host_reports_controller.rb
class HostReportsController < ApplicationController
  before_action :get_events

  respond_to :html, :text

  def show
    @is_form = true
    respond_with(@events)
  end

  def update
    if params[:commit] == t('actions.marked_done')
      Event.where(['id IN (?)', event_ids]).update_all(done: true)
    end
    redirect_to show_host_report_url(ip: host)
  end

  def new_mail
    @is_form = true
    @message = "Unchecked events are always done"
  end

  def create_mail
    if mail_params[:mail_to].present?
      ReportMailer.host_event_report(mail_params.merge(event_ids: event_ids).to_h).deliver_later
      if mark_done?
        Event.where(['id IN (?)', event_ids]).update_all(done: true)
      end
      flash[:success] = "Success"
      redirect_to show_host_report_url(ip: mail_params[:ip])
    else
      flash[:error] = "Error"
      render 'new_mail', locals: { ip: mail_params[:ip] }
    end
  end

private

  def get_events
     @events = Event.not_ignored.by_network(host).most_current(50)
  end

  def event_ids
    params[:event_ids] || []
  end

  def mark_done?
   params[:mark_done].present?
  end

  def host
    @host = params[:ip]
  end

  def mail_params
    params.permit(:utf8, :_method, :authenticity_token, :commit, :id,
      :ip, :mail_to, :mail_cc, :subject, :message).reject{|_, v| v.blank?}
  end
end

app/helpers/host_reports_helper.rb
module HostReportsHelper
  def host_report_link(ip)
    link_to(
      icon_hsquare, show_host_report_path(ip: ip), 
        class: "btn btn-outline-secondary btn-sm mr-1", 
        title: "host report"
    )
  end

  def icon_hsquare
    raw("<i class='fas fa-h-square'></i>")
  end

end

app/views/host_reports/_event.html.erb
<div style="padding-bottom: 1em; line-height: 20px;">
  <div style="font-weight: bold;">
    <% if @is_form %>
      <%= check_box_tag "event_ids[]", event.id, !event.done, class: "multicheck" %>
    <% end %>
    <%= link_to("#{event.sensor} #{event.event_time.to_s(:precision)}", event_url(event)) %>
    <%= link_to("[#{event.alert_signature_id}] #{event.alert_signature} [#{event.alert_category}]", signature_url(event.signature)) %>
  </div>
  <div style="padding-left: 20px">
    {<%= event.proto %>} <%= event.src_ip %>:<%= event.src_port %> (<%=IpLookup.hostname(event.src_ip)%>) -> <%= event.dst_ip %>:<%= event.dst_port %> (<%= IpLookup.hostname(event.dst_ip)%>)
  </div>
<% if event.has_http %>
  <div style="padding-left: 20px">
    <%= event.http_method %> <%= event.http_hostname %> <%= event.http_url%> [<%= event.http_status %>] size:<%= event.http_length %>
  </div>
<% end %>
</div>

app/views/host_reports/_event.text.erb
<%= event.sensor %> <%= event.event_time.to_s(:precision) %> [<%= event.alert_signature_id %>] <%= event.alert_signature %> [<%= event.alert_category %>] 
    {<%= event.proto %>} <%= event.src_ip %>:<%= event.src_port %> (<%=IpLookup.hostname(event.src_ip)%>) -> <%= event.dst_ip %>:<%= event.dst_port %> (<%= IpLookup.hostname(event.dst_ip)%>)
<% if event.has_http %>
    <%= event.http_method %> <%= event.http_hostname %> <%= event.http_url%> [<%= event.http_status %>] size:<%= event.http_length %>
<% end %>

app/views/host_reports/_host_report.html.erb
<h1> Current events for: <%= host.to_s%> </h1>

<% if @message.present? %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <p><%= @message %></p>
  </div>
<% end %>
<%= hidden_field_tag "ip", @host %>

<div class="checkbox">
  <label>
    <%= check_box_tag "checkAll" %> <%= t('actions.mark_all') %> 
  </label>
</div>
<br />

<%= render(partial: 'host_reports/event', collection: events) || "No events available" %>

app/views/host_reports/_host_report.text.erb
Current events for: <%= host.to_s%>
==================================

<%= @message if @message.present? %>

<%= render(partial: 'host_reports/event', collection: events) || "No events available" %>

app/views/host_reports/new_mail.html.erb
<%= form_tag(create_mail_host_report_path,
    class: 'form-horizontal card') do |f| %>

  <div class="card-header">
    <legend>Create Mail for Host Events</legend>
  </div>
  <div class="card-body">

    <div class="form-group row">
      <label for="ip" class='col-sm-2 col-form-label'>Host:</label>
      <div class="col-sm-10">
	<input type="string" class="form-control" id="ip" 
	 name="ip" value="<%=@host%>" placeholder="ip address" />
      </div>
    </div>
    <div class="form-group row">
      <label for="mail_to" class='col-sm-2 col-form-label'>Mail to:</label>
      <div class="col-sm-10">
	<input type="email" class="form-control" id="mail_to" 
	 name="mail_to" placeholder="Email" value="<%=Lackmus.default_recipient%>" />
      </div>
    </div>
    <div class="form-group row">
      <label for="mail_cc" class='col-sm-2 col-form-label'>Mail cc:</label>
      <div class="col-sm-10">
	<input type="email" class="form-control" id="mail_cc" 
	 name="mail_cc" placeholder="Email" />
      </div>
    </div>
    <div class="form-group row">
      <label for="subject" class='col-sm-2 col-form-label'>Subject:</label>
      <div class="col-sm-10">
	<input type="string" class="form-control" id="subject" 
	 name="subject" placeholder="subject" />
      </div>
    </div>
    <div class="form-group row">
      <label for="message" class='col-sm-2 col-form-label'>Additional info:</label>
      <div class="col-sm-10">
	<textarea rows="5" class="form-control" id="message" name="message" ></textarea>
      </div>
    </div>
    <div class="form-group row">
      <div class="offset-sm-2 col-sm-10">
	<div class="checkbox">
	  <label>
	    <%= check_box_tag "mark_done", 1, true %> <%= t('actions.marked_done') %>
	  </label>
	</div>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-sm-12">
	<%= submit_tag t('actions.submit'), :class => 'btn btn-primary' %>
	<%= cancel_button %>
      </div>
    </div>
  </div>
  <div class="card-body">
    <div class="form-group row">
      <div class="col-sm-12">
	<%= render partial: 'host_report', locals: {host: @host, events: @events} %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-sm-12">
	<%= submit_tag t('actions.submit'), :class => 'btn btn-primary' %>
	<%= cancel_button %>
      </div>
    </div>
  <% end %>
</div>

app/views/host_reports/show.html.erb
<%= form_tag update_host_report_path,
    method: :post, class: 'form-horizontal'  do %>

<%= render partial: 'host_report', locals: {host: @host, events: @events} %>

<br />
<div role="toolbar">
  <%= link_to t('actions.send_mail'), new_mail_host_report_path(ip: @host), class: 'btn btn-primary' %>
  <%= submit_tag(t('actions.marked_done'), class: "btn btn-success",
          data: {confirm: "#{t('lackmus.really')} #{t('actions.marked_done')}?"})%>
</div>

<% end %>

app/views/host_reports/show.text.erb
<%= render partial: 'host_report', locals: {host: @host, events: @events} %>